### PR TITLE
Add golang default images

### PR DESCRIPTION
**Pull request by wbobeirne**
Grabs go 1.15.3, sets up PATH and GOROOT. Not sure if there's anything else we should be doing.

### CODE REVIEW

**Review by fuskovic — CHANGES_REQUESTED** [review]
Playing with the centos golang image I noticed `GOBIN` is not set when poking around in the container :

```
[coder@6c6d0938b028 /]$ go env GOPATH GOBIN GOROOT
/home/coder/go

/usr/local/go
```

We need `GOBIN` set and exported in `PATH` so:

1 - `go get` can install binaries there and...
2-  `coder` can run binaries in `GOBIN` from anywhere.

We also don't need to set `GOROOT` as it gets set already for us.

Maybe something like: 

```
# Setup go env vars
ENV PATH=$PATH:/usr/local/go/bin
ENV GOPATH=/home/coder/go
ENV GOBIN=$GOPATH/bin
ENV PATH=$PATH:$GOBIN
ENV GO111MODULE=on
```

Now when we check inside the container : 

```
[coder@3bd850aa5aa9 /]$ go env GOPATH GOBIN GOROOT
/home/coder/go
/home/coder/go/bin
/usr/local/go
``` 

I noticed in the above envs if `GO111MODULE` is set to `off` or `auto` we still fail to install a remote binary from inside the container:

```
go get -u github.com/kkdai/youtube/v2
```

Setting `GO111MODULE` to `on` solves that problem and will let us install remote binaries without problems from the beginning.

Also noticed If src, bin, and pkg are :

1. not owned by coder
2. haven't been created yet
3. and you use go get to install something...

`go get` will try to create them in `GOPATH` and fail with a permissions error.
if we just create those as `coder` from the start we can mitigate that and don't have to chown stuff so putting this after the envs would solve that problem :

```
USER coder

RUN mkdir -p $GOPATH/{src,pkg,bin}
```

@tychoish might have some thoughts on what we should be putting in here as well.

**Comment by wbobeirne** [comment]
@fuskovic thanks for the notes, I updated the env vars as you suggested and actually installed some modules this time.

I didn't add the `GO111MODULE` var by default though, since my understanding was that that's kind of a holdover from an older version of Go, and as far as I can tell some modules seem to install fine (I tested with https://github.com/davecheney/httpstat for instance.) It seems to me like that's a bit of an opinionated thing to flip on by default, and that most Go devs would know to use it when they need it. But I don't spend a lot of time in Go land, so I could be totally off base.

Let me know if I'm wrong, and I'd be happy to update it.

**Comment by tychoish** [comment]
I think it's legit to omit go11module setting. These look fine to me.

**Comment by deansheather** [comment]
GOBIN isn't required. Go will install stuff to `$GOPATH/bin` by default. I've never had to set GOBIN before.

**Comment by fuskovic** [comment]
It will install it but it won't be able to find the binary if `$GOBIN` is not exported to your `$PATH`

> GOBIN isn't required. Go will install stuff to `$GOPATH/bin` by default. I've never had to set GOBIN before.

@deansheather this is the behavior I observed playing inside the container.

Without `GOBIN` set

```
[coder@3e14a9530d63 /]$ go env GOPATH GOBIN 
/home/coder/go

[coder@3e14a9530d63 /]$ go get github.com/davecheney/httpstat
[coder@3e14a9530d63 /]$ httpstat
bash: httpstat: command not found
[coder@3e14a9530d63 /]$ 
```

With `GOBIN` set and exported to my `$PATH`

```
[coder@d543cefe0ba2 /]$ go env GOPATH GOBIN 
/home/coder/go
/home/coder/go/bin
[coder@d543cefe0ba2 /]$ go get github.com/davecheney/httpstat
[coder@d543cefe0ba2 /]$ httpstat
Usage: httpstat [OPTIONS] URL

OPTIONS:
  -4	resolve IPv4 addresses only
  -6	resolve IPv6 addresses only
  -E string
    	client cert file for tls config
  -H value
    	set HTTP header; repeatable: -H 'Accept: ...' -H 'Range: ...'
  -I	don't read body of request
  -L	follow 30x redirects
  -O	save body as remote filename
  -X string
    	HTTP method to use (default "GET")
  -d string
    	the body of a POST or PUT request; from file use @filename
  -k	allow insecure SSL connections
  -o string
    	output file for body
  -v	print version number

ENVIRONMENT:
  HTTP_PROXY    proxy for HTTP requests; complete URL or HOST[:PORT]
                used for HTTPS requests if HTTPS_PROXY undefined
  HTTPS_PROXY   proxy for HTTPS requests; complete URL or HOST[:PORT]
  NO_PROXY      comma-separated list of hosts to exclude from proxy
```

**Review by fuskovic — APPROVED** [review]

**Pull request merged**
