### PR TITLE
Revert "Remove VNC images (#38)"

### PR DESCRIPTION
**Pull request by bpmct**
I tested a build locally, but am not sure if the GitHub actions CI will fail. I will make any changes to fix the CI builds.

cc @ericpaulsen

### CODE REVIEW

**Comment by vapurrmaid** [comment]
@bpmct was this just a revert?

**Comment by bpmct** [comment]
@vapurrmaid I cherry-picked the commit into this branch

**Comment by jawnsy** [comment]
I suggest we do this in two stages, revert the deletion first, and then [modify the build scripts](https://github.com/cdr/enterprise-images/blob/main/scripts/images.sh) so that we have nightly builds for this image.

Unfortunately we don't really have a great way to test these images other than locally at present :frowning:

**Comment by bpmct** [comment]
> so that we have nightly builds for this image.

Any reason this should be done nightly versus explicitly when changes were made to the `images/vnc` folder?

**Comment by bpmct** [comment]
ah nevermind, I see your scheduled builds for the other images. probably to ensure the enterprise-base is up to date?
 
I'll do some digging and try to replicate. if I'm understanding correctly, the build of this action should be in another action entirely?

**Comment by jawnsy** [comment]
@bpmct It's done nightly because the base images change periodically, and this allows us to get security updates (otherwise we would only pick up security updates whenever we manually update the images). The builds are also not reproducible currently, and as a consequence it means that we get the latest GoLand etc in each build.

Nightly is probably the wrong cadence (too frequent) and I didn't really put much thought into it

**Comment by bpmct** [comment]
So are we good to merge this? Then I just add `vnc` to this script?

https://github.com/cdr/enterprise-images/blob/main/scripts/images.sh

**Comment by jawnsy** [comment]
If it's just a revert, I think using `git revert id` is better than cherry-pick because it's more clear what happened? It seems like that was what Grey was getting at

**Comment by vapurrmaid** [comment]
> @vapurrmaid I cherry-picked the commit into this branch

I'd suggest a clean revert of https://github.com/cdr/enterprise-images/commit/25eaa0bfd1dda2a6fc0977d8fd64e875c20aa4b8

**Comment by vapurrmaid** [comment]
@bpmct Personally, the actions I'd take are:

```
git checkout add-vnc
git fetch origin
git reset --hard origin/master
git revert 25eaa0bfd1dda2a6fc0977d8fd64e875c20aa4b8
git commit # if needed, I forget
git push -f
```

The reason I'm suggesting this is it makes review and the git history much cleaner and easier to read about

**Comment by bpmct** [comment]
Gotcha, I wasn't entirely following at first. I appreciate the steps 🙏

**Comment by vapurrmaid** [comment]
> Gotcha, I wasn't entirely following at first. I appreciate the steps

It's all good @bpmct !

**Comment by vapurrmaid** [comment]
I suspect CI will fail the build for the same reason it failed in https://github.com/cdr/enterprise-images/pull/37 - however we know and understand this presently.

**Review by vapurrmaid — APPROVED** [review]

**Comment by vapurrmaid** [comment]
https://github.com/cdr/enterprise-images/pull/37#pullrequestreview-553838610 may still hold as a feasible next step should we need to

**Comment by bpmct** [comment]
> [#37 (review)](https://github.com/cdr/enterprise-images/pull/37#pullrequestreview-553838610) may still hold as a feasible next step should we need to

Makes sense, I am happy to do that. However the root cause may be that it fails to build under the sysbox runtime, which should be fixed anyways so that VNCs can run on CVMs.

**Comment by jawnsy** [comment]
I think if we merge this it won't build since we haven't added it to the images list, and in the follow up we can add it and fix the build issue then? These builds also happen in VMs since it's on GitHub's public infra

**Pull request merged**
